environment:
  matrix:
    - RUST_TOOLCHAIN: 1.22.1

cache:
  - '%USERPROFILE%\.cargo'
  - '%USERPROFILE%\.nuget\packages'
  - '%LOCALAPPDATA%\Cargo\script-cache'
  - '%LOCALAPPDATA%\Cargo\binary-cache'
  - '%APPVEYOR_BUILD_FOLDER%\SafeApp.AppBindings.Android\lib'
  - '%APPVEYOR_BUILD_FOLDER%\SafeApp.AppBindings.Desktop\lib'
  - '%APPVEYOR_BUILD_FOLDER%\SafeApp.AppBindings.iOS\lib'
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib

clone_depth: 1

image: Visual Studio 2017

install:
  - choco install resharper-clt.portable
  - ps: |
        $url = "https://github.com/maidsafe/QA/raw/master/appveyor/install_rustup.ps1"
        Invoke-WebRequest $url -OutFile "install_rustup.ps1"
        . ".\install_rustup.ps1"
  - bash -lc "curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh"
  - bash -lc "PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH; bash cargo_install.sh cargo-script"
  - cargo script DownloadNativeLibs.crs

platform:
  - x64

before_build:
  - cd SafeApp.Tests.Core

build_script:
  - dotnet build --runtime win10-x64

after_build:
  - nuget restore ..\SafeApp.sln
  - InspectCode.exe -o=resharper-clt-output.xml ..\SafeApp.sln
  - ps: |
        $result = [xml](Get-Content .\resharper-clt-output.xml)
        $result.Report.Issues.ChildNodes | ForEach-Object {
          $project = $_.Name
          $_.ChildNodes | ForEach-Object {
            if ($_ -ne $null) {
              Add-AppveyorCompilationMessage -Category Error -Message $_.TypeId -Details $_.Message -Line $_.Line -FileName $_.File -ProjectName $project
              $lint_failed = $true
            }
          }
        }
        if ($lint_failed) {
          $host.UI.WriteErrorLine("Code inspection failed. Please check the 'Messages' tab.")
          $host.SetShouldExit(99)
        } else {
          Add-AppveyorCompilationMessage -Category Information -Message "No code issues."
        }

test_script:
  - dotnet test --logger="trx;LogFileName=results.xml"

after_test:
  - ps: |
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResults\results.xml))
